n1= int (input('escreva um numero :'))
n2 = int (input ('escreva um numero ::') )
resul= (n1+n2)
print ('seu resultado é {} + {} = {}'.format (n1,n2 ,resul))
n1= int (input('escreva um numero '))
n2 = int (input ('escreva um numero') )
resul= (n1+n2)
print ('seu resultado é {}'.format (resul))
